# fly.toml app configuration file generated for ruby-on-vibes-template
app = "ruby-on-vibes-template"
primary_region = "ord"

[build]
  buildpacks = ["heroku/ruby"]

[env]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/up"

[processes]
  web = "bin/rails server -p 3000 -b 0.0.0.0"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
