# fly.toml app configuration file generated for ruby-on-vibes-template
app = "ruby-on-vibes-template"
primary_region = "ord"

[build]
  buildpacks = ["heroku/ruby"]

# Remove release_command - volumes not available during release phase

[env]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"

[[mounts]]
  source = "app_data"
  destination = "/mnt/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

# Ensure sufficient memory for Rails migrations
[vm]
  memory = "512mb"

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/up"

[processes]
  web = "bin/rails fly:server"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
